version: '3.7'

services:
  nginx_test:
    image: nginx:stable-alpine
    container_name: nginx_test
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_test
      - mysql_test
    links:
      - app_test
      - mysql_test

  app_test:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_test
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql_test
      - rabbitmq
    links:
      - mysql_test
      - rabbitmq

  mysql_test:
    image: mysql:latest
    container_name: mysql_test
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: notifications
      MYSQL_USER: ns_user
      MYSQL_PASSWORD: ns_password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_test
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    container_name: rabbitmq
    volumes:
      - rabbitvolume:/data
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  rabbitvolume: {}